services:
  - type: web
    name: campus-facility-booking-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
